language: python

# needed to use trusty
sudo: required

dist: xenial

python:
  - "2.7"
  - "3.6"

install:
  - sudo apt-get install -y libffi-dev
  - wget -O /tmp/file.tar.xz http://archive.ubuntu.com/ubuntu/pool/main/f/file/file_5.32.orig.tar.xz
  - cd /tmp && xz -cd /tmp/file.tar.xz | tar x && cd -
  - cd /tmp/file-5.32 && ./configure && make && make install && cd -
  - pip install coverage
  - python setup.py install

script:
  - coverage run setup.py test

after_success:
  - pip install coveralls && coveralls
  - pip install codecov && codecov
