on: [push, pull_request]

name: CI

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install libmagic (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
            wget -O /tmp/file.tar.gz http://archive.ubuntu.com/ubuntu/pool/main/f/file/file_5.38.orig.tar.gz
            cd /tmp && tar zxf file.tar.gz && cd -
            cd /tmp/file-5.38 && ./configure --prefix=/usr/local && make && sudo make install && cd -
      - name: Install libmagic (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install libmagic
      - name: Run test cases
        run: |
            pip install coverage
            python setup.py install
            coverage run setup.py test
